services:
  guacamole:
    image: guacamole/guacamole
    ports:
      - 8080:8080
    env_file: .guac.env
    volumes:
      - guac-bowl-data:/opt/guacamole/extensions/guacamole-auth-jdbc/postgresql/schema:ro
    environment:
      GUACD_HOSTNAME: guacd-host
      POSTGRESQL_HOSTNAME: postgres-host
    depends_on:
      - guacd

  guacd:
    image: guacamole/guacd
    hostname: guacd-host

  db:
    image: postgres
    hostname: postgres-host
    env_file: .db.env
    volumes:
      - guac-bowl-data:/docker-entrypoint-initdb.d:ro
    depends_on:
      - guacamole

volumes:
  guac-bowl-data:
