#! /bin/bash

psql -U postgres -d $GUACAMOLE_DATABASE <<-EOSQL
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $GUACAMOLE_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $GUACAMOLE_USER;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $GUACAMOLE_USER;
EOSQL